#!/bin/sh

help() {
cat << EOF
suto - get sudo timeout status

suto simply returns the current sudo timeout status.

usage: suto [-h] | [-ve]

Results:
  0: sudo is not timed out - the user **will not** need to re-enter their password to run sudo
  1: sudo is timed out     - the user   **will**   need to re-enter their password to run sudo

Options:
  -h            Print this message and exit
  -v            Print verbose output to stderr
  -e            Exit with result as exit code

Notes:
  Remember that the result of this command is only valid for the exact moment it is run.
  It's possible the sudo timeout will expire immediately after this command is run.

EOF
}

v=0
e=0

while getopts "hve" opt; do
	case $opt in
		h) help; exit;;
		v) v=1;;
		e) e=1;;
	esac
done

main() {
	sudo -n true &> /dev/null
	r=$?
	echo $r
	if [[ $v == 1 ]]; then
		if [[ $r == 1 ]]; then
			echo "sudo is timed out - the user will need to re-enter their password to run sudo" >&2
		else
			echo "sudo is not timed out - the user will not need to re-enter their password to run sudo" >&2
		fi
	fi
	if [[ $e == 1 ]]; then
		exit $r
	fi
}

main
